### ISSUE TITLE
Update profile page

### ISSUE THREAD

**Issue by BernardoSM** [menthorlabs/menthor#14]

**Comment by BernardoSM** [comment]
Gabriel Olegário:


- Os badges estão sem nome e, ao passar o mouse neles, também não sei sobre o que se tratam. Seria uma boa inserir um nome para o badge e um subtitle de como ele é adquirido.

- Ao lado da foto de perfil, abaixo de "conquistas" há o número 0/???. Essa barra de progresso estilo 9999/10000 denota que, ou haverá um limite de pontos de conquista ou os badges darão um valor de XP que aumentará algum tipo de nível no perfil. Se não tiver nível e nem limite, talvez o "/???" fique confuso ou polua o perfil.

- Eu consegui editar meu perfil clicando no nome, mas por curiosidade, pois não há opção nas configs e nem nada que sinalize a possibilidade de edição. Sei que a galera é inteligente e curiosa e vai achar, mas talvez um botãozinho ou ícone ao lado do nome possa ajudar, e um hover na foto para aparecer um ícone de edição.

**Comment by lfelipessilva** [comment]
Os badges na verdade já tem "mostram" a descrição e o nome, o problema é que só deles tem estes campos definidos. Pode explicar como cada um deles é adquirido pra que eu adicione nos campos?

**Comment by lfelipessilva** [comment]
Outra coisa que pensei foi adicionar o ícone de edit no hover da imagem, mas ao invés de abrir o modal de edição, abrirmos direto o seletor de imagem pra fazer o update direto da página de profile. Mas isso implicaria na duplicação do código de edição da imagem. Acha que é uma boa?

**Comment by BernardoSM** [comment]
Opa @lfelipessilva desculpa a demora. Adicionei os efeitos de hover no [figma](https://www.figma.com/file/Sh5CPFW4qWX8ZV4OPClOzo/Menthor---Apps?type=design&node-id=901%3A7760&mode=design&t=XDJtlcMwep11WYit-1), só adicionar por favor e adicionar a label de "Não Disponível" nas outras badges.

A gente não tem definido ainda como vamos disponibilizar as próximas badges, por isso não tem nenhuma informação nelas.

Não precisa duplicar o código de edição de imagem, pode deixar abrindo o modal mesmo.

Obrigado!
