### ISSUE TITLE
Change top shadow colors when hover course images or open a course

### ISSUE THREAD

**Issue by BernardoSM** [menthorlabs/menthor#16]
Adicionar: https://github.com/lokesh/color-thief

**Comment by Clerijr** [comment]
Maybe i didnt completely understood this issue. We should take the collor pallete from the course image using the library color thief and applying the dominant color in the course component top shadow??

**Comment by BernardoSM** [comment]
Ei @Clerijr é isso mesmo. Pra exemplificar melhor, quando você der o hover em um curso, devemos atualizar a cor do shadow lá em cima:

![image](https://github.com/menthorlabs/menthor/assets/36281298/f38143aa-689e-4c99-b580-fb6ac082600a)

A mesma coisa vale para pra quando abrir o curso, deverá ser atualizado a cor da shadow pra cor dominante do curso.

**Comment by nicolaswalcker** [comment]
A shadow com o uso do colorthief seria utilizando a paleta da imagem e apenas substituindo os valores que estão nas sombras atuais ou utlizar apenas a cor predominante?
Outra coisa, na home caso o mouse não esteja nos links do curso, a cor volta a ser a padrão, certo?

**Comment by BernardoSM** [comment]
Fala @nicolaswalcker

Faz um teste, se conseguir usar a cor primária e secundária e ficar legal, pode deixar assim. Se ficar ruim, deixa só a cor primária da paleta, daí tu atualiza as duas sombras com a mesma cor.

Isso mesmo, se tirar o hover de qualquer curso a cor volta ser a rosa/azul.

**Comment by BernardoSM** [comment]
Ficou muito foda @nicolaswalcker 

Obrigado pela contribuição! <3
