### ISSUE TITLE
Alterar rota do botão Início na página de Cursos e adicionar novo botão

### ISSUE THREAD

**Issue by the-physicist** [menthorlabs/menthor#19]
Reparei que depois que acessamos a página dos cursos (`/app`) só há uma forma de voltar para home (`/`), que é clicando na setinha de navegação que aponta para a esquerda (destaque número 2 da imagem em anexo).

Achei contraintuitivo não ser o botão `Início` (destaque número 1 da imagem em anexo).

![image](https://github.com/menthorlabs/menthor/assets/60639536/38a223c9-1d7d-492a-bd92-fc1e9a45ec35)

Sugiro, portanto, que a rota do botão `Início` seja alterada de `/app` para `/`, assim os estudantes podem voltar mais facilmente para a tela inicial.

E para contornar a falta de um botão que redirecione para `/app`, recomendo a criação do botão `Cursos` (ou Todos os Cursos, por exemplo) entre o botão `Início` e `Buscar`. Ficaria mais ou menos dessa forma:

![image](https://github.com/menthorlabs/menthor/assets/60639536/27efec3a-0065-4834-96b1-36acdb6e668a)

**Comment by BernardoSM** [comment]
Ei @the-physicist tudo bem? Seu ponto é muito válido, mas a ideia seria remover o acesso à landing page se a pessoa tiver logada, muito semelhante com o que acontece aqui no github, na resend.com e na vercel.com

Vou fechar essa issue porque pretendemos melhorar isso no futuro, só que de uma forma diferente.

Fique à vontade para reabrir se quiser acrescentar algo.

**Comment by the-physicist** [comment]
Entendi, Bernardo, me parece uma boa ideia fazer isso mesmo!
Aguardarei então.

Abraço.
