### ISSUE TITLE
stargazers_count is not updating

### ISSUE THREAD

**Issue by ericviana** [menthorlabs/menthor#2]
Wrong amount
![image](https://github.com/menthorlabs/menthor/assets/76598237/9e6b09eb-a7ec-448f-a128-5676f8880a38)

Right amount
![image](https://github.com/menthorlabs/menthor/assets/76598237/f2eb160e-22de-469b-94ab-a31c6ce5688f)

**Comment by BernardoSM** [comment]
Ei @ericviana 

Na verdade como a landing page é um SSG, só vai atualizar a quantidade de stars na hora que buildarmos uma versão nova. Não vejo como um problema nesse momento mostrar as stars atualizadas em tempo real, então vou fechar essa issue por agora.

**Comment by ericviana** [comment]
TMS
