### ISSUE TITLE
Criação de Guia de Contribuição e Comunicação em Português

### ISSUE THREAD

**Issue by the-physicist** [menthorlabs/menthor#23]
Olá humanos,

Gostaria de propor a criação de um Guia de Contribuição para o projeto. Um `Guia de Contribuição` é essencial para facilitar o processo de integração de novos colaboradores e para garantir que todos estejam na mesma página em relação aos padrões e práticas de desenvolvimento do projeto, possibilitando facilitar até a manutenção.

**Motivação:**

1. **Comunicação em Português:** Considerando que nosso projeto visa oferecer cursos gratuitos na área de TI, acredito que a comunicação em português seja mais acessível para iniciantes e para a maioria dos nossos colaboradores. Isso permitirá que todos compreendam as discussões e as contribuições de forma mais eficaz.

3. **Padrão de Comunicação:** Precisamos estabelecer que a comunicação será predominantemente em português (_commits_, discussões, repositório etc), mas as linhas de código e os comentários poderiam ser em inglês até para servir de prática.

4. **Padrão de Estilo:** Um padrão de estilo é fundamental para manter a consistência em todo o código, na estrutura dos diretórios, nos _commits_ e nas mensagens de _commit_. Isso tornará o projeto mais fácil de manter e ajudará a evitar problemas causados por diferenças de estilo ou na comunicação.

**O que proponho:**

1. Especificar que a comunicação principal será em português.

2. Estabelecer um padrão de estilo para o código, incluindo formatação, nomenclatura de variáveis, estrutura de diretórios e mensagens de _commit_. Isso será detalhado no Guia de Contribuição criado por nós (ou se basear em algum existente).

O que acham?

**Comment by BernardoSM** [comment]
Fala @the-physicist adorei a ideia, só o item 2 da proposta que não entendi direito. Hoje em dia o "estilo do código" é gerenciado pelo prettier/eslint, as mensagens de commit pra mim não tem tanta diferença ser em inglês ou português...

Agora eu concordo que deveríamos padronizar a comunicação de issues, discussions, etc. Como o projeto é voltado 100% para o público nacional, deveríamos sim mantê-lo tudo em português.

Você tem algum exemplo de Guia de Contribuição que achou legal? Gostaria de saber mais sobre isso, obrigado!!

**Comment by the-physicist** [comment]
Salve, @BernardoSM!

Então, eu pensei em coisas mais simples como criar as tags (fix, feat, style, refactor, test, docs, etc); definir se deve ser maiúscula ou minúsculas (FIX, Fix ou fix); se será em português ou inglês; ressaltar a importância de fazer commits pequenos; quando usar ou não descrição além do título....sabe? Definir coisas nesse sentido.

Penso que isso ajudaria porque além de criar um padrão que facilita a leitura/manutenção, também remove essa responsabilidade na decisão de quem vai contribuir. Por exemplo, eu levei muito tempo para decidir se eu deveria falar em inglês ou português; se eu deveria abrir Issue ou fazer PR diretamente; se eu deveria usar as tags...fiquei em dúvida porque vi várias pessoas fazendo isso de formas diferentes. E iniciantes, que acredito serem o público-alvo do projeto, provavelmente vão ter dúvidas semelhantes.

Sobre oo Guia de Contribuição, eu pensei em seguir algumas convenções de boas práticas de commits. Poderíamos usar uma combinação do _[conventional commits](https://www.conventionalcommits.org/pt-br/v1.0.0/)_ com o [gitmoji](https://github.com/carloscuesta/gitmoji), por exemplo.

Eu posso fazer uma primeira versão e apresentar aqui para vocês, se quiser. Só me avisa que eu faço!

**Comment by Shnrqpdr** [comment]
Eu não gosto muito do [gitmoji](https://github.com/carloscuesta/gitmoji) por achar que polui um pouco a mensagem, mas sem dúvidas o [conventional commits](https://www.conventionalcommits.org/pt-br/v1.0.0/) ajudaria bastante, na minha opinião é até estéticamente mais bonito escrever as mensagens seguindo os conventional commits.

**Comment by BernardoSM** [comment]
Opa @the-physicist você pode fazer uma versão somente com conventional commits? Também acho que o gitmoji polui um pouco como o @Shnrqpdr comentou.

Obrigado!

**Comment by BernardoSM** [comment]
Ótimo trabalho @mikaelhadler . Ei @the-physicist vou fechar essa issue mas se tiver mais algo que vê sentido em melhorar, pode abrir novamente.

**Comment by the-physicist** [comment]
Fala, @BernardoSM.

Então, dei uma olhada e algumas coisas me deixaram confuso. Eu não entendi porque os arquivos de template possuem apenas links de sessão com o conteúdo comentado. Tô em dúvida se é assim porque está esperando alguém contribuir ou se é o template finalizado de fato. E aparentemente esse modelo de template não é mais recomendado pelo GitHub, talvez seja interessante atualizar.

![image](https://github.com/menthorlabs/menthor/assets/60639536/fcf36b7e-142e-4446-9cb4-2223bca03ad2)

Eu também não entendi porque o arquivo [CONTRIBUTING.md](https://github.com/menthorlabs/menthor/blob/main/CONTRIBUTING.md) é curtinho assim sem revelar os detalhes do guia. É para redirecionar para os respectivos templates de _issue_ e _pull request_? Não é mais interessante detalhar tudo no mesmo arquivo CONTRIBUTING.md?

São questões realmente para eu entender como o @mikaelhadler pensou em estruturar o guia.

Quando eu levantei esse ponto do guia, pensei apenas em um arquivo de contribuição detalhando os padrões de commit, boas práticas do projeto e enfatizando o uso do português. Além disso, pensei também em adicionar parte disso no README.md. Não pensei em templates em si (o que é uma boa ideia, aliás). Eu acho que o template faz sentido porque assim que a pessoa entra nas páginas de _issue_ ou _pull request_ ela automaticamente vê a mensagem para ler o guia, assim: 
![image](https://github.com/menthorlabs/menthor/assets/60639536/a1d50aef-c8c2-48a5-b370-d1d4a1174929)

Segue alguns exemplos de Guia de Contribuição que eu pensei para o projeto:

- https://contributing.md/example/
- https://github.com/atom/atom/blob/master/CONTRIBUTING.md
- https://github.com/github/docs/blob/main/CONTRIBUTING.md
- https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md

[Esse aqui](https://github.com/cezaraugusto/github-template-guidelines/blob/master/.github/CONTRIBUTING.md) parece estar no formato que o `Mikael` pensou. E eu gosto dele.

Aguardo a decisão as considerações de vocês para submeter minhas contribuições.

Abraço!

**Comment by mikaelhadler** [comment]
Olá @the-physicist, eu entendo o ponto que você levantou sobre o template de abertura de issues. Talvez fosse mais claro para os usuários se as informações não fossem apenas comentários, mas estivessem visíveis. O que você acha?

> E aparentemente esse modelo de template não é mais recomendado pelo GitHub, talvez seja interessante atualizar.

Eu não tenho certeza a que modelo você se refere nesta seção. Poderia especificar qual arquivo não está dentro do padrão?

>  Eu também não entendi porque o arquivo [CONTRIBUTING.md](https://github.com/menthorlabs/menthor/blob/main/CONTRIBUTING.md) é curtinho assim sem revelar os detalhes do guia. É para redirecionar para os respectivos templates de issue e pull request? Não é mais interessante detalhar tudo no mesmo arquivo CONTRIBUTING.md?

Minha intenção ao simplificar as informações era criar um ponto de partida flexível e permitir que os contribuidores acrescentassem o que achassem relevante. Se achar que alguma informação importante está faltando, seria ótimo se você pudesse abrir um pull request e discutir as adições necessárias. 

Fiquei realmente impressionado com as observações que você fez, @the-physicist. Acredito que seria uma ótima primeira contribuição se você pudesse criar um pull request com essas sugestões e correções. Se estiver com pouco tempo, também é possível abrir uma issue e atribuí-la a mim, e eu contribuirei assim que possível.

Caso tenha passado algo a mais despercebido, vamos discutindo abraço :]

**Comment by the-physicist** [comment]
Olá, @mikaelhadler.

Peço desculpas se te ofendi de alguma forma, eu realmente só não tinha entendido se sua contribuição estava finalizada ou era a base para suportar novas contribuições. Agora eu entendi que os _templates_ são arquivos que surgem quando alguém abre uma nova _issue_ ou _PR_. Eu inicialmente achei que era apenas um arquivo _markdown_, por isso questionei a formatação deles.

Sobre o Guia de Contribuição, acabei de enviar a PR #29 com a forma que imaginei o arquivo CONTRIBUTING. Também criei um Código de Conduta e fiz a atualização do README para a nova seção.

Se vocês gostarem eu atualizo os arquivos de _template_ em breve.

**Comment by mikaelhadler** [comment]
Fala @the-physicist relaxa, de forma alguma você me ofendeu, talvez a forma como eu respondi tenha dado a entender isso, se for isso me desculpe também :heart:, amanhã pela tarde já faço a revisão.
