### ISSUE TITLE
Ancoras não estão funcionando conforme o esperado no ambiente local

### ISSUE THREAD

**Issue by mikaelhadler** [menthorlabs/menthor#27]
# O que aconteceu?
Segui as instruções disponíveis no [README](./README.md) para rodar o ambiente local, mas por algum motivo as âncoras não estão apontando para o endereço correto, a aplicação está rodando na porta 3001 e as âncoras apontando para 3002, fazendo com que a navegação quebre e exiba a página padrão para rotas não encontradas.

# O que era esperado?
Que as âncoras fossem direcionadas para o endereço e porta correta

# Capturas de tela
![image](https://github.com/menthorlabs/menthor/assets/6784777/45f518c9-1d43-4da6-8c84-671f1a6fc069)

**Comment by BernardoSM** [comment]
Ei @mikaelhadler acho que esqueci de atualizar a variável de ambiente `NUXT_PUBLIC_APP_URL=http://localhost:3001/`.

Você pode testar atualizar pra http://localhost:3002/ e testar novamente por gentileza?

Lembrando que nesse caso você terá que rodar os dois projetos em conjunto, ou seja, `yarn dev --filter=www` e `yarn dev --filter=app`.

**Comment by mikaelhadler** [comment]
@BernardoSM descobri o problema. Não há nenhuma necessidade de mudança nas environments, o real problema é o que o [README.md](https://github.com/menthorlabs/menthor/blob/main/README.md#como-rodar-na-sua-m%C3%A1quina) não informa da necessidade de rodar as duas aplicações simultaneamente. 

Após rodar ambas em simultâneo, tudo funcionou perfeitamente.

PR de correção aberto.

**Comment by mikaelhadler** [comment]
Resolvido no PR #28
