### ISSUE TITLE
Enhance error message display

### ISSUE THREAD

**Issue by gabrielgomeso** [menthorlabs/menthor#3]
This is probably a minor issue, but when I tried to log in with my GitHub account, I got redirected to the register page, and I didn't quite figure out how and why. I thought there weren't any error messages, so I tried again and just then I saw a toast warning in the corner left of the screen.
I suggest changing the side of the toast, increasing it, and setting a smooth red border or background color to grab the user's attention a little more.

<details>
<summary>Screenshot</summary>

![image](https://github.com/menthorlabs/menthor/assets/17833683/b9acc481-0af5-444b-93b5-265065089ae1)

See how even in a laptop screen size it's a lot of white and the error doesn't have enough contrast?
</details>

Anyway, I loved the project and hope to contribute to it anytime soon

**Comment by BernardoSM** [comment]
See https://github.com/menthorlabs/menthor/pull/4.

**Comment by BernardoSM** [comment]
Fala @gabrielgomeso , acho que como o projeto é voltado para o público nacional, não tem problema abrir as issues em português.

Sobre o toast de erro, eu tentei deixar o mais minimalista possível, mas agora eu percebi que realmente vai ser melhor atualizar. Vou tentar ver mais algumas inspirações e trago atualizações quando tiver algo.

**Comment by gabrielgomeso** [comment]
Perfeito! Eu tava em dúvida se abria em inglês ou português, então segui o da outra issue haha. Se encontrar algum design e quiser mandar aqui, posso tentar implementar!!

**Comment by BernardoSM** [comment]
Fala @gabrielgomeso desculpa a demora. Você pode atualizar pra esse [design aqui](https://www.figma.com/file/Sh5CPFW4qWX8ZV4OPClOzo/Menthor---Apps?type=design&node-id=901%3A8249&mode=design&t=XDJtlcMwep11WYit-1)?

Obrigado!
