### ISSUE TITLE
Incluir success message ao enviar imagem de conclusão de atividade

### ISSUE THREAD

**Issue by aylmerbolzan** [menthorlabs/menthor#34]
# O que aconteceu?
Há o redirecionamento automático para a aula seguinte, após enviar a imagem de conclusão da atividade da aula.

# O que era esperado?
Seria interessante que tivesse uma mensagem de "Enviado com Sucesso" ou alguma notificação visual para que o usuário veja que obteve sucesso no envio e que está sendo redirecionado para a próxima aula, não ficando dúvidas se a aula anterior foi concluída ou não.

**Comment by BernardoSM** [comment]
Ei @aylmerbolzan subi uma atualização hoje com essa feature, vou fechar aqui mas se encontrar algum bug sinta-se a vontade para reabrir a issue.
