### ISSUE TITLE
Corrigir preview de atividades já enviadas - Access Denied

### ISSUE THREAD

**Issue by aylmerbolzan** [menthorlabs/menthor#35]
# O que aconteceu?
Se voltar num exercício já enviado em aulas anteriores, ao clicar novamente para *Enviar Tarefa*, abre o modal de upload com o preview da *submission image* quebrado, com *Access Denied*.

# O que era esperado?

1.  Corrigir o preview que carrega quebrado.
2.  Uma sinalização no "Enviar Tarefa" para que esteja claro que a tarefa já foi enviada, como por exemplo, renomear a label para "Reenviar Tarefa"

# Capturas de tela
![image](https://github.com/menthorlabs/menthor/assets/110077540/51a8c98c-f703-4505-965a-a52d8e190f1d)

**Comment by BernardoSM** [comment]
Ei @aylmerbolzan subi uma atualização hoje com essa feature, vou fechar aqui mas se encontrar algum bug sinta-se a vontade para reabrir a issue.
