### ISSUE TITLE
Finalizar aula ao clicar em "Próxima aula"

### ISSUE THREAD

**Issue by aylmerbolzan** [menthorlabs/menthor#36]
# O que aconteceu? O que era esperado?
Ao invés ter a necessidade de clicar em "Finalizar aula" e depois seguir clicando em "Próxima aula", seria interessante que, ao clicar em _"Próxima aula"_, automaticamente já desse a aula como finalizada.

**Comment by BernardoSM** [comment]
Ei @aylmerbolzan subi uma atualização hoje com essa feature, vou fechar aqui mas se encontrar algum bug sinta-se a vontade para reabrir a issue.
