### ISSUE TITLE
Índice lateral não acompanha o curso escolhido na busca

### ISSUE THREAD

**Issue by marlonangeli** [menthorlabs/menthor#40]
# O que aconteceu?

Ao alterar o curso pela busca, o índice lateral não altera de acordo com o curso.

# O que era esperado?

Alterar o índice lateral conforme o curso selecionado, sem ter que voltar na página inicial ou recarregar a página.

# Capturas de tela

![video](https://github.com/menthorlabs/menthor/assets/73134662/72f6a6af-c7cd-4ffe-804d-eff2d7c4c039)

**Comment by BernardoSM** [comment]
Opa, obrigado por reportar esse bug, vou verificar esse final de semana

**Comment by BernardoSM** [comment]
Consertei na pr https://github.com/menthorlabs/menthor/pull/41
