### ISSUE TITLE
Trocar Bem Vindo por Olá

### ISSUE THREAD

**Issue by mrarticuno** [menthorlabs/menthor#7]
Pensei na possibilidade de trocar Bem vindo(a) por Olá que não depende de genero e evita de ter que implementar opção de genero de pronome.

**Comment by the-physicist** [comment]
Concordo com a ideia, Gabriel. Parece mais viável que criar todo um sistema para diferenciar gêneros/pronomes e remove a necessidade de registrar essa informação no perfil.

Ainda nesse tópico, levanto a discussão sobre a troca das variações de **`aluno`**. Acredito que para deixar o projeto mais confortável poderíamos substituir por **`estudante`**, que é realmente neutro. Talvez não seja o termo que mais gera "identificação", mas é o mais inclusivo e tenho tentado usar sempre que posso.

**Comment by Nick-Gabe** [comment]
Eu apoio, acho que `estudante` iria manter uma linguagem neutra inclusiva e ao mesmo tempo passar a mensagem de que a pessoa é "mentorada", tal qual a palavra `aluno` diz.

**Comment by BernardoSM** [comment]
Obrigado pelo feedback galera! Por enquanto resolvemos aqui mas fiquem a vontade para abrir novamente.
